spring.application.name=firstspringdemo
spring.datasource.url=jdbc:postgresql://localhost:5432/firstspringdemodb
spring.datasource.username=serpentwyvern
spring.datasource.password=HelionTokamak6891!!!
spring.datasource.driver-class-name=org.postgresql.Driver
