spring.application.name=firstspringdemo
spring.datasource.url=jdbc:postgresql://localhost:5432/firstspringdemodb?currentSchema=inventory_management,public
spring.datasource.username=serpentwyvern
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
